require: rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'config/**/*'

Layout/LineLength:
  Max: 100

Metrics/BlockLength:
  Exclude:
    - config/**/*

Style/Documentation:
  Enabled: false