require: rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'node_modules/**/*'

Layout/LineLength:
  Max: 100

Metrics/BlockLength:
  Max: 100
  Exclude:
    - config/**/*

Style/Documentation:
  Enabled: false

Lint/MissingSuper:
  Exclude:
    - 'app/services/**/*'
